// Путь для сохранения ответов API
export const API_RESPONSES_DIR = './storage/api-responses';

export const LANGUAGES = [
    { "name": "English", "code": "en" },
    { "name": "Spanish", "code": "es" },
    { "name": "Arabic", "code": "ar" },
    { "name": "Vietnamese", "code": "vi" },
    { "name": "Thai", "code": "th" },
    { "name": "German", "code": "de" },
    { "name": "Indonesian", "code": "id" },
    { "name": "Portuguese", "code": "pt" },
    { "name": "French", "code": "fr" },
    { "name": "Malay", "code": "ms" },
    { "name": "Dutch", "code": "nl" },
    { "name": "Japanese", "code": "ja" },
    { "name": "Italian", "code": "it" },
    { "name": "Romanian", "code": "ro" },
    { "name": "Chinese - Traditional", "code": "zh" }, // Note: "zh" is used for Chinese, with variants like zh-Hant for Traditional
    { "name": "Korean", "code": "ko" }
  ];

export const COUNTRIES = {
    Afghanistan: "AF",
    Albania: "AL",
    Algeria: "DZ",
    Andorra: "AD",
    Angola: "AO",
    AntiguaAndBarbuda: "AG",
    Argentina: "AR",
    Armenia: "AM",
    Australia: "AU",
    Austria: "AT",
    Azerbaijan: "AZ",
    Bahamas: "BS",
    Bahrain: "BH",
    Bangladesh: "BD",
    Barbados: "BB",
    Belarus: "BY",
    Belgium: "BE",
    Belize: "BZ",
    Benin: "BJ",
    Bhutan: "BT",
    Bolivia: "BO",
    BosniaAndHerzegovina: "BA",
    Botswana: "BW",
    Brazil: "BR",
    Brunei: "BN",
    Bulgaria: "BG",
    BurkinaFaso: "BF",
    Burundi: "BI",
    Cambodia: "KH",
    Cameroon: "CM",
    Canada: "CA",
    CapeVerde: "CV",
    CentralAfricanRepublic: "CF",
    Chad: "TD",
    Chile: "CL",
    China: "CN",
    Colombia: "CO",
    Comoros: "KM",
    Congo: "CG",
    CostaRica: "CR",
    Croatia: "HR",
    Cuba: "CU",
    Cyprus: "CY",
    CzechRepublic: "CZ",
    DemocraticRepublicOfTheCongo: "CD",
    Denmark: "DK",
    Djibouti: "DJ",
    Dominica: "DM",
    DominicanRepublic: "DO",
    EastTimor: "TL",
    Ecuador: "EC",
    Egypt: "EG",
    ElSalvador: "SV",
    EquatorialGuinea: "GQ",
    Eritrea: "ER",
    Estonia: "EE",
    Eswatini: "SZ",
    Ethiopia: "ET",
    Fiji: "FJ",
    Finland: "FI",
    France: "FR",
    Gabon: "GA",
    Gambia: "GM",
    Georgia: "GE",
    Germany: "DE",
    Ghana: "GH",
    Greece: "GR",
    Grenada: "GD",
    Guatemala: "GT",
    Guinea: "GN",
    GuineaBissau: "GW",
    Guyana: "GY",
    Haiti: "HT",
    Honduras: "HN",
    Hungary: "HU",
    Iceland: "IS",
    India: "IN",
    Indonesia: "ID",
    Iran: "IR",
    Iraq: "IQ",
    Ireland: "IE",
    Israel: "IL",
    Italy: "IT",
    IvoryCoast: "CI",
    Jamaica: "JM",
    Japan: "JP",
    Jordan: "JO",
    Kazakhstan: "KZ",
    Kenya: "KE",
    Kiribati: "KI",
    Kuwait: "KW",
    Kyrgyzstan: "KG",
    Laos: "LA",
    Latvia: "LV",
    Lebanon: "LB",
    Lesotho: "LS",
    Liberia: "LR",
    Libya: "LY",
    Liechtenstein: "LI",
    Lithuania: "LT",
    Luxembourg: "LU",
    Madagascar: "MG",
    Malawi: "MW",
    Malaysia: "MY",
    Maldives: "MV",
    Mali: "ML",
    Malta: "MT",
    MarshallIslands: "MH",
    Mauritania: "MR",
    Mauritius: "MU",
    Mexico: "MX",
    Micronesia: "FM",
    Moldova: "MD",
    Monaco: "MC",
    Mongolia: "MN",
    Montenegro: "ME",
    Morocco: "MA",
    Mozambique: "MZ",
    Myanmar: "MM",
    Namibia: "NA",
    Nauru: "NR",
    Nepal: "NP",
    Netherlands: "NL",
    NewZealand: "NZ",
    Nicaragua: "NI",
    Niger: "NE",
    Nigeria: "NG",
    NorthKorea: "KP",
    NorthMacedonia: "MK",
    Norway: "NO",
    Oman: "OM",
    Pakistan: "PK",
    Palau: "PW",
    Panama: "PA",
    PapuaNewGuinea: "PG",
    Paraguay: "PY",
    Peru: "PE",
    Philippines: "PH",
    Poland: "PL",
    Portugal: "PT",
    Qatar: "QA",
    Romania: "RO",
    Russia: "RU",
    Rwanda: "RW",
    SaintKittsAndNevis: "KN",
    SaintLucia: "LC",
    SaintVincentAndTheGrenadines: "VC",
    Samoa: "WS",
    SanMarino: "SM",
    SaoTomeAndPrincipe: "ST",
    SaudiArabia: "SA",
    Senegal: "SN",
    Serbia: "RS",
    Seychelles: "SC",
    SierraLeone: "SL",
    Singapore: "SG",
    Slovakia: "SK",
    Slovenia: "SI",
    SolomonIslands: "SB",
    Somalia: "SO",
    SouthAfrica: "ZA",
    SouthKorea: "KR",
    SouthSudan: "SS",
    Spain: "ES",
    SriLanka: "LK",
    Sudan: "SD",
    Suriname: "SR",
    Sweden: "SE",
    Switzerland: "CH",
    Syria: "SY",
    Taiwan: "TW",
    Tajikistan: "TJ",
    Tanzania: "TZ",
    Thailand: "TH",
    Togo: "TG",
    Tonga: "TO",
    TrinidadAndTobago: "TT",
    Tunisia: "TN",
    Turkey: "TR",
    Turkmenistan: "TM",
    Tuvalu: "TV",
    Uganda: "UG",
    Ukraine: "UA",
    UnitedArabEmirates: "AE",
    UnitedKingdom: "GB",
    UnitedStates: "US",
    Uruguay: "UY",
    Uzbekistan: "UZ",
    Vanuatu: "VU",
    VaticanCity: "VA",
    Venezuela: "VE",
    Vietnam: "VN",
    Yemen: "YE",
    Zambia: "ZM",
    Zimbabwe: "ZW"
};